In [1]:
from Chapter2.CreateDataset import CreateDataset
import pandas as pd
import matplotlib.pyplot as plt
import os
import copy
from util.VisualizeDataset import VisualizeDataset
from util import util

In [2]:
rawdatapath = "data/raw/"
outputpath = "data/intermediate/"
givenpath = "data/given/"

if not os.path.exists(outputpath):
    print("Empty path, so creating..." + outputpath + "...done!")
    os.makedirs(outputpath)

In [3]:
accraw = pd.read_csv(rawdatapath + "Accelerometer.csv")
timecol = "Time (s)"
accfeatures = list()
for col in accraw:
    if (col != timecol) and \
    (col != "Absolute acceleration (m/s^2)"):
        accfeatures.append(col)
accfeatures

['Acceleration x (m/s^2)', 'Acceleration y (m/s^2)', 'Acceleration z (m/s^2)']

In [4]:
accraw

,Time (s),Acceleration x (m/s^2),Acceleration y (m/s^2),Acceleration z (m/s^2),Absolute acceleration (m/s^2)
0,0.018694,-1.977070,7.584650,6.073283,9.915669
1,0.021144,-2.020140,7.582257,6.054141,9.910812
2,0.023594,-2.003391,7.591828,6.054141,9.914739
3,0.026045,-2.008176,7.579864,6.056533,9.908012
4,0.028495,-1.993819,7.591828,6.020641,9.892385
...,...,...,...,...,...
124856,300.012150,-2.254936,7.548757,5.733502,9.743794
124857,300.014552,-2.257329,7.560721,5.735895,9.755026
124858,300.016956,-2.235794,7.536793,5.757431,9.744231
124859,300.019358,-2.245365,7.541579,5.764609,9.754373
124860,300.021760,-2.259722,7.541579,5.769394,9.760516

In [5]:
accgiven = pd.read_csv(givenpath + "accelerometer_phone.csv")
timecol = "Time (s)"
accfeatures_given = list()
for col in accgiven:
    if (col != timecol) and \
    (col != "Absolute acceleration (m/s^2)"):
        accfeatures_given.append(col)
accfeatures_given

['sensor_type', 'device_type', 'timestamps', 'x', 'y', 'z']

In [6]:
accgiven

           sensor_type device_type           timestamps      x      y      z
0        accelerometer  smartphone  1454956105656222395 -0.087  0.181  9.621
1        accelerometer  smartphone  1454956105660105781 -0.069  0.153  9.663
2        accelerometer  smartphone  1454956105667091406 -0.073  0.156  9.647
3        accelerometer  smartphone  1454956105670696615 -0.070  0.184  9.623
4        accelerometer  smartphone  1454956105675807552 -0.059  0.171  9.625
...                ...         ...                  ...    ...    ...    ...
1604601  accelerometer  smartphone  1454964064977354323 -0.166  0.178  9.628
1604602  accelerometer  smartphone  1454964064982928229 -0.174  0.183  9.643
1604603  accelerometer  smartphone  1454964064987681354 -0.174  0.183  9.643
1604604  accelerometer  smartphone  1454964064992564896 -0.154  0.177  9.666
1604605  accelerometer  smartphone  1454964064996744531 -0.159  0.203  9.629

[1604606 rows x 6 columns]

In [8]:
acctime = pd.read_csv(rawdatapath + "Accelerometer_time.csv")
acctime

   event  experiment time   system time                   system time text
0  START         0.000000  1.622380e+09  2021-05-30 21:08:32.654 UTC+08:00
1  PAUSE       300.027308  1.622380e+09  2021-05-30 21:13:32.681 UTC+08:00

In [10]:
acctime["system time"][0]

1622380112.654

In [14]:
accraw["Time (s)"] = accraw["Time (s)"] + acctime["system time"][0]

In [15]:
accraw

,Time (s),Acceleration x (m/s^2),Acceleration y (m/s^2),Acceleration z (m/s^2),Absolute acceleration (m/s^2)
0,1.622380e+09,-1.977070,7.584650,6.073283,9.915669
1,1.622380e+09,-2.020140,7.582257,6.054141,9.910812
2,1.622380e+09,-2.003391,7.591828,6.054141,9.914739
3,1.622380e+09,-2.008176,7.579864,6.056533,9.908012
4,1.622380e+09,-1.993819,7.591828,6.020641,9.892385
...,...,...,...,...,...
124856,1.622380e+09,-2.254936,7.548757,5.733502,9.743794
124857,1.622380e+09,-2.257329,7.560721,5.735895,9.755026
124858,1.622380e+09,-2.235794,7.536793,5.757431,9.744231
124859,1.622380e+09,-2.245365,7.541579,5.764609,9.754373
124860,1.622380e+09,-2.259722,7.541579,5.769394,9.760516

In [26]:
accraw.to_csv("test.csv")

In [33]:
test = pd.read_csv(rawdatapath + "test.csv")
test

,Unnamed: 0,Time (s),Acceleration x (m/s^2),Acceleration y (m/s^2),Acceleration z (m/s^2),Absolute acceleration (m/s^2)
0,0,1.622380e+09,-1.977070,7.584650,6.073283,9.915669
1,1,1.622380e+09,-2.020140,7.582257,6.054141,9.910812
2,2,1.622380e+09,-2.003391,7.591828,6.054141,9.914739
3,3,1.622380e+09,-2.008176,7.579864,6.056533,9.908012
4,4,1.622380e+09,-1.993819,7.591828,6.020641,9.892385
...,...,...,...,...,...,...
124856,124856,1.622380e+09,-2.254936,7.548757,5.733502,9.743794
124857,124857,1.622380e+09,-2.257329,7.560721,5.735895,9.755026
124858,124858,1.622380e+09,-2.235794,7.536793,5.757431,9.744231
124859,124859,1.622380e+09,-2.245365,7.541579,5.764609,9.754373
124860,124860,1.622380e+09,-2.259722,7.541579,5.769394,9.760516

In [16]:
granularities = [60000, 250]
datasets = []

In [29]:
for g in granularities:
    
    Dataset = CreateDataset(rawdatapath, g)
    
    Dataset.add_numerical_dataset("test.csv", timecol, accfeatures, "avg", "acc_")
    
    dataset = Dataset.data_table
    print(dataset)
#     Dataviz = VisualizeDataset()
    
#     Dataviz.plot_dataset_boxplot(dataset, ['acc_Acceleration x (m/s^2)', 'acc_Acceleration y (m/s^2)', 'acc_Acceleration z (m/s^2)'])

Reading data from test.csv
                              acc_Acceleration x (m/s^2)  \
1970-01-01 00:00:01.622380112                   -1.65954

                              acc_Acceleration y (m/s^2)  \
1970-01-01 00:00:01.622380112                    7.35627

                              acc_Acceleration z (m/s^2)
1970-01-01 00:00:01.622380112                     6.1556
Reading data from test.csv
                              acc_Acceleration x (m/s^2)  \
1970-01-01 00:00:01.622380112                   -1.65954

                              acc_Acceleration y (m/s^2)  \
1970-01-01 00:00:01.622380112                    7.35627

                              acc_Acceleration z (m/s^2)
1970-01-01 00:00:01.622380112                     6.1556

In [30]:
dataset

,acc_Acceleration x (m/s^2),acc_Acceleration y (m/s^2),acc_Acceleration z (m/s^2)
1970-01-01 00:00:01.622380112,-1.65954,7.35627,6.1556